import BookingForm from "./booking-form";
import WhatsAppAssistant from "./whatsapp-assistant";
const services = [
 ["Vehicle servicing","Routine and major servicing for the road ahead."],["Diagnostics","Investigate warning lights and performance concerns."],["Brakes","Inspection and repair of braking components."],["Suspension","Assessment and repair of ride and handling concerns."],["Engine repairs","Mechanical diagnosis and repairs."],["Clutch repairs","Inspection and repair of clutch operation."],["Gearbox repairs","Diagnosis and transmission repairs."],["Tyres & wheels","Tyre and wheel services for your drive."]
];
export function GarageHome({demo=false}:{demo?:boolean}){return <main>{demo&&<div className="demo-banner"><strong>GF GARAGE · INTERACTIVE DEMO</strong><span>Explore the website and try a sample booking.</span><a href="/demo/staff">TRY THE STAFF DASHBOARD ↗</a></div>}
 <header className="header"><a className="logo" href="#top">GF<span>.</span><small>GARAGE</small></a><nav><a href="#services">Services</a><a href="#about">About</a><a href="#reviews">Reviews</a><a href="#contact">Contact</a><a href={demo?"/demo/staff":"/staff"}>Staff bookings</a></nav><a className="nav-cta" href="#booking">BOOK ONLINE ↗</a></header>
 <section className="hero" id="top"><div className="wrap hero-inner"><p className="kicker">GF GARAGE / OTTERY, CAPE TOWN</p><h1>Your vehicle.<br/><em>In good hands.</em></h1><p>Servicing, diagnostics and repairs in Cape Town. Tell us what your vehicle needs and request an appointment online.</p><div className="actions"><a className="button" href="#booking">BOOK AN APPOINTMENT ↗</a><a className="outline" href="https://wa.me/27726135470" target="_blank" rel="noreferrer">WHATSAPP US ↗</a></div></div><span className="hero-end">AUTOMOTIVE CARE • OTTERY</span></section>
 <div className="ribbon"><div className="wrap ribbon-grid"><div><b>24/7 online requests</b><span>Book at a time that suits you</span></div><div><b>Conveniently in Ottery</b><span>Cape Town, South Africa</span></div><div><b>Service to repair</b><span>Vehicle care in one place</span></div></div></div>
 <section className="section wrap" id="services"><div className="section-intro"><div><p className="kicker">01 / WHAT WE DO</p><h2>Care for every<br/><em>kilometre ahead.</em></h2></div><p>From routine servicing to mechanical concerns, find the right starting point for your vehicle.</p></div><div className="services">{services.map(([name,description],i)=><article key={name}><span className="index">0{i+1} / SERVICE</span><div className="service-icon">✳</div><h3>{name}</h3><p>{description}</p><a href="#booking">BOOK THIS SERVICE ↗</a></article>)}</div></section>
 <section className="about" id="about"><div className="wrap about-grid"><div className="monogram">GF<span>.</span><small>BUILT AROUND YOUR DRIVE</small></div><div><p className="kicker">02 / THE WORKSHOP</p><h2>Good service starts with a clear conversation.</h2><p>At GF Garage in Ottery, you can bring us your servicing and repair concerns. Tell us what is happening with your vehicle, and our team can arrange the next step.</p><a href="#booking">TELL US ABOUT YOUR VEHICLE ↗</a></div></div></section>
 <section className="section booking" id="booking"><div className="wrap booking-grid"><div><p className="kicker">03 / APPOINTMENTS</p><h2>Ready when<br/><em>you are.</em></h2><p>Send an appointment request at any hour. We will review your preferred date and contact you to confirm availability.</p><ol><li><b>01</b><span>Tell us about your vehicle<small>Choose a service and describe the concern.</small></span></li><li><b>02</b><span>Choose a preferred time<small>Request the date that works for you.</small></span></li><li><b>03</b><span>Wait for confirmation<small>The workshop confirms your appointment.</small></span></li></ol></div><BookingForm demo={demo}/></div></section>
 <section className="section wrap reviews" id="reviews"><p className="kicker">04 / CUSTOMER VOICES</p><div className="section-intro"><h2>Real experiences.<br/><em>Real feedback.</em></h2><div><p>Verified customer reviews will appear here once GF Garage provides approved feedback.</p><a href="https://www.facebook.com/GlobalFortuneGarage/" target="_blank" rel="noreferrer">VISIT OUR FACEBOOK PAGE ↗</a></div></div></section>
 <section className="contact" id="contact"><div className="wrap contact-grid"><div><p className="kicker">05 / FIND US</p><h2>Let’s get you<br/><em>back on the road.</em></h2><p>Visit the workshop or send us a request online. Confirm the address with GF Garage before travelling.</p><a className="button" href="#booking">REQUEST AN APPOINTMENT ↗</a></div><div className="contact-card"><p>WORKSHOP LOCATION</p><h3>Unit 4A, 16 Crete Road<br/>Ottery, Cape Town</h3><small>Address pending business confirmation</small><a href="https://www.google.com/maps/search/?api=1&query=Unit+4A+16+Crete+Road+Ottery+Cape+Town" target="_blank" rel="noreferrer">GET DIRECTIONS ↗</a><hr/><p>CALL OR WHATSAPP</p><a href="tel:+27726135470">072 613 5470</a><a href="https://wa.me/27726135470" target="_blank" rel="noreferrer">CHAT ON WHATSAPP ↗</a><a href="https://www.facebook.com/GlobalFortuneGarage/" target="_blank" rel="noreferrer">GF Garage on Facebook ↗</a><small>Email and operating hours will be added after confirmation.</small></div></div></section>
 <footer><div className="wrap footer"><a className="logo" href="#top">GF<span>.</span><small>GARAGE</small></a><div><a href="#services">SERVICES</a><a href="#booking">BOOKING</a><a href="#contact">CONTACT</a><a href="/privacy">PRIVACY</a><a href={demo?"/demo/staff":"/staff"}>STAFF BOOKINGS</a></div><small>© 2026 GF Garage · Ottery</small></div></footer>
 <WhatsAppAssistant demo={demo}/></main>}

export default function Home(){return <GarageHome/>}
