"use client";
import {useState} from "react";
import {MessageCircle,ArrowUpRight} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogTrigger} from "@/components/ui/dialog";
import {Button} from "@/components/ui/button";
export default function WhatsAppAssistant({demo=false}:{demo?:boolean}){
 const [topic,setTopic]=useState("");const [name,setName]=useState("");const [vehicle,setVehicle]=useState("");const [detail,setDetail]=useState("");
 const message=["Hello GF Garage,",topic&&"I would like help with "+topic+".",name&&"Name: "+name,vehicle&&"Vehicle: "+vehicle,detail&&"Details: "+detail,"Please contact me about the next step."].filter(Boolean).join("\n");
 return <Dialog><DialogTrigger asChild><Button className="wa-launch"><MessageCircle size={22}/> WhatsApp assistant</Button></DialogTrigger><DialogContent className="wa-dialog"><div className="wa-heading"><MessageCircle size={28}/><div><DialogTitle>GF Garage assistant</DialogTitle><DialogDescription>Prepare a message for 072 613 5470</DialogDescription></div></div><p className="wa-bubble">Hello! What can we help you with today?</p><div className="wa-options">{["Book a service","Request a repair quote","Ask about tyres","Follow up on a booking","Speak to the team"].map(item=><Button variant="outline" key={item} aria-pressed={topic===item} onClick={()=>setTopic(item)} className={topic===item?"wa-selected":""}>{item}</Button>)}</div>{topic&&<div className="wa-details"><p className="wa-bubble">Add a few details and we’ll prepare your message. You can review it in WhatsApp before sending.</p><label htmlFor="wa-name">Your name</label><input id="wa-name" value={name} onChange={e=>setName(e.target.value)} maxLength={80}/><label htmlFor="wa-vehicle">Vehicle make and model</label><input id="wa-vehicle" value={vehicle} onChange={e=>setVehicle(e.target.value)} maxLength={100}/><label htmlFor="wa-detail">{topic==="Follow up on a booking"?"Booking reference or registration":"How can we help?"}</label><textarea id="wa-detail" value={detail} onChange={e=>setDetail(e.target.value)} maxLength={1000}/><a className="wa-send" href={"https://wa.me/27726135470?text="+encodeURIComponent(message)} target="_blank" rel="noreferrer">CONTINUE IN WHATSAPP <ArrowUpRight size={18}/></a></div>}<p className="wa-note">{demo?"Demo: Continue in WhatsApp opens the real business chat. Nothing is sent until you press Send in WhatsApp. ":""}This guided assistant prepares your message. The GF Garage team replies on WhatsApp; appointments still need confirmation.</p></DialogContent></Dialog>
}
