"use client";
import {useEffect,useState} from "react";
import {loadDemoBookings,setDemoBookings,sampleBookings,type DemoBooking} from "@/lib/demo-bookings";
import {Button} from "@/components/ui/button";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
export default function DemoStaff(){
 const [rows,setRows]=useState<DemoBooking[]>(sampleBookings);const [filter,setFilter]=useState("all");const [notice,setNotice]=useState("");
 useEffect(()=>setRows(loadDemoBookings()),[]);
 function update(reference:string,status:string){const next=rows.map(row=>row.reference===reference?{...row,status}:row);try{setDemoBookings(next);setRows(next);setNotice(reference+" changed to "+status+". This is a demo; no customer was contacted.");}catch{setNotice("Your browser could not save the demo change. Allow session storage to continue.");}}
 function reset(){try{setDemoBookings(sampleBookings);setRows(sampleBookings);setNotice("Example bookings restored.");}catch{setNotice("Could not reset the demo.");}}
 return <main className="demo-dashboard"><header className="demo-dash-header"><a className="logo" href="/demo">GF<span>.</span><small>GARAGE</small></a><a href="/demo">← CUSTOMER WEBSITE</a></header><div className="wrap section"><p className="kicker">INTERACTIVE DEMO / SAMPLE DATA ONLY</p><h1 style={{fontSize:"clamp(36px,5vw,58px)"}}>Your workshop, at a glance.</h1><p className="demo-intro">Try changing a booking status, or return to the website to create a sample request. No sign-in is needed for this demonstration.</p><div className="demo-stats">{["pending","confirmed","completed"].map(status=><div key={status}><span>{status}</span><strong>{rows.filter(row=>row.status===status).length}</strong></div>)}</div><div className="demo-toolbar"><label htmlFor="demo-filter">Show requests</label><Select value={filter} onValueChange={setFilter}><SelectTrigger id="demo-filter" className="demo-select"><SelectValue/></SelectTrigger><SelectContent>{["all","pending","confirmed","completed","cancelled"].map(status=><SelectItem key={status} value={status}>{status==="all"?"All requests":status}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={reset}>Reset demo</Button><a className="button" href="/demo#booking">TRY A NEW BOOKING ↗</a></div>{notice&&<p className="form-status" role="status">{notice}</p>}<div className="demo-requests">{rows.filter(row=>filter==="all"||row.status===filter).map(row=><article key={row.reference} className="demo-request"><div className="demo-request-heading"><div><span className="kicker">{row.reference}</span><h2>{row.name}</h2></div><span className={"demo-badge "+row.status}>{row.status}</span></div><div className="demo-request-details"><div><small>VEHICLE</small><strong>{row.make}</strong><span>{row.registration}</span></div><div><small>SERVICE</small><strong>{row.service}</strong></div><div><small>PREFERRED APPOINTMENT</small><strong>{row.date}</strong><span>{row.time}</span></div></div><p>{row.message}</p><div className="demo-toolbar"><label htmlFor={row.reference}>Change status</label><Select value={row.status} onValueChange={value=>update(row.reference,value)}><SelectTrigger id={row.reference} className="demo-select"><SelectValue/></SelectTrigger><SelectContent>{["pending","confirmed","completed","cancelled"].map(status=><SelectItem key={status} value={status}>{status}</SelectItem>)}</SelectContent></Select></div></article>)}</div>{rows.filter(row=>filter==="all"||row.status===filter).length===0&&<p>No demo requests match this filter.</p>}<p className="demo-intro">This dashboard uses fictional records and requests created in this browser tab. The live staff dashboard and customer records remain protected.</p></div></main>
}
